// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dut_dense_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_st1_fsm_0 = 9'b1;
parameter    ap_ST_st2_fsm_1 = 9'b10;
parameter    ap_ST_st3_fsm_2 = 9'b100;
parameter    ap_ST_pp0_stg0_fsm_3 = 9'b1000;
parameter    ap_ST_pp0_stg1_fsm_4 = 9'b10000;
parameter    ap_ST_pp0_stg2_fsm_5 = 9'b100000;
parameter    ap_ST_pp0_stg3_fsm_6 = 9'b1000000;
parameter    ap_ST_pp0_stg4_fsm_7 = 9'b10000000;
parameter    ap_ST_st37_fsm_8 = 9'b100000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv32_C4000000 = 32'b11000100000000000000000000000000;
parameter    ap_const_lv32_40000000 = 32'b1000000000000000000000000000000;
parameter    ap_const_lv32_3D800000 = 32'b111101100000000000000000000000;
parameter    ap_const_lv9_100 = 9'b100000000;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv10_200 = 10'b1000000000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv23_0 = 23'b00000000000000000000000;
parameter    ap_const_lv5_2 = 5'b10;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] input_r_address0;
output   input_r_ce0;
input  [0:0] input_r_q0;
output  [9:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [0:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;
reg output_r_ce0;
reg output_r_we0;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_26;
wire   [7:0] b_fc1_address0;
reg    b_fc1_ce0;
wire   [31:0] b_fc1_q0;
wire   [16:0] w_fc1_address0;
reg    w_fc1_ce0;
wire   [0:0] w_fc1_q0;
reg   [31:0] one_out_reg_131;
reg   [9:0] m_reg_143;
wire   [31:0] grp_fu_154_p2;
reg   [31:0] reg_174;
reg    ap_sig_cseq_ST_pp0_stg1_fsm_4;
reg    ap_sig_69;
reg    ap_reg_ppiten_pp0_it4;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it2;
reg    ap_reg_ppiten_pp0_it3;
reg    ap_reg_ppiten_pp0_it5;
reg    ap_reg_ppiten_pp0_it6;
reg   [0:0] ifzero_reg_352;
reg   [0:0] ap_reg_ppstg_ifzero_reg_352_pp0_iter4;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_3;
reg    ap_sig_97;
reg   [0:0] ap_reg_ppstg_ifzero_reg_352_pp0_iter5;
wire   [8:0] n_1_fu_186_p2;
reg   [8:0] n_1_reg_308;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_112;
wire   [0:0] exitcond1_fu_180_p2;
reg   [9:0] output_addr_reg_318;
wire   [16:0] n_cast4_fu_198_p1;
reg   [16:0] n_cast4_reg_323;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_128;
reg   [31:0] b_fc1_load_reg_328;
wire   [0:0] exitcond_fu_202_p2;
reg   [0:0] exitcond_reg_333;
reg   [0:0] ap_reg_ppstg_exitcond_reg_333_pp0_iter1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_333_pp0_iter2;
wire   [9:0] m_3_fu_208_p2;
reg   [9:0] m_3_reg_337;
wire   [0:0] ifzero_fu_241_p2;
reg   [0:0] ap_reg_ppstg_ifzero_reg_352_pp0_iter1;
reg   [0:0] ap_reg_ppstg_ifzero_reg_352_pp0_iter2;
reg   [0:0] ap_reg_ppstg_ifzero_reg_352_pp0_iter3;
reg   [0:0] ap_reg_ppstg_ifzero_reg_352_pp0_iter6;
wire   [0:0] tmp_7_fu_253_p2;
reg   [0:0] tmp_7_reg_356;
reg    ap_sig_cseq_ST_pp0_stg2_fsm_5;
reg    ap_sig_166;
wire   [31:0] grp_fu_166_p1;
reg   [31:0] tmp_11_reg_366;
reg   [31:0] one_out_1_reg_371;
wire   [31:0] grp_fu_160_p2;
reg   [31:0] tmp_8_reg_377;
reg   [31:0] one_out_2_reg_382;
wire   [0:0] tmp_15_fu_299_p2;
reg   [0:0] tmp_15_reg_387;
reg    ap_sig_cseq_ST_pp0_stg4_fsm_7;
reg    ap_sig_198;
reg   [8:0] n_reg_119;
reg    ap_sig_cseq_ST_st37_fsm_8;
reg    ap_sig_215;
reg   [31:0] one_out_phi_fu_135_p4;
reg    ap_sig_cseq_ST_pp0_stg3_fsm_6;
reg    ap_sig_223;
reg   [9:0] m_phi_fu_147_p4;
wire   [63:0] tmp_4_fu_192_p1;
wire   [63:0] newIndex8_fu_231_p1;
wire   [63:0] tmp_6_fu_236_p1;
reg   [31:0] grp_fu_154_p0;
reg   [31:0] grp_fu_154_p1;
reg   [31:0] grp_fu_160_p0;
reg   [31:0] grp_fu_160_p1;
wire   [31:0] grp_fu_166_p0;
wire   [8:0] tmp_21_fu_214_p1;
wire   [16:0] tmp_9_fu_218_p3;
wire   [16:0] w_index_fu_226_p2;
wire   [0:0] tmp1_fu_247_p2;
wire   [31:0] biased_to_int_fu_263_p1;
wire   [7:0] tmp_fu_267_p4;
wire   [22:0] tmp_22_fu_277_p1;
wire   [0:0] notrhs_fu_287_p2;
wire   [0:0] notlhs_fu_281_p2;
wire   [0:0] tmp_13_fu_293_p2;
wire   [0:0] tmp_14_fu_169_p2;
reg   [8:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'b1;
#0 ap_reg_ppiten_pp0_it4 = 1'b0;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_ppiten_pp0_it3 = 1'b0;
#0 ap_reg_ppiten_pp0_it5 = 1'b0;
#0 ap_reg_ppiten_pp0_it6 = 1'b0;
end

dut_dense_1_b_fc1 #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
b_fc1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b_fc1_address0),
    .ce0(b_fc1_ce0),
    .q0(b_fc1_q0)
);

dut_dense_1_w_fc1 #(
    .DataWidth( 1 ),
    .AddressRange( 131072 ),
    .AddressWidth( 17 ))
w_fc1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_fc1_address0),
    .ce0(w_fc1_ce0),
    .q0(w_fc1_q0)
);

dut_fadd_32ns_32ns_32_5_full_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_fadd_32ns_32ns_32_5_full_dsp_U118(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_154_p0),
    .din1(grp_fu_154_p1),
    .ce(1'b1),
    .dout(grp_fu_154_p2)
);

dut_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_fmul_32ns_32ns_32_4_max_dsp_U119(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_160_p0),
    .din1(grp_fu_160_p1),
    .ce(1'b1),
    .dout(grp_fu_160_p2)
);

dut_sitofp_32ns_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_sitofp_32ns_32_6_U120(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_166_p0),
    .ce(1'b1),
    .dout(grp_fu_166_p1)
);

dut_fcmp_32ns_32ns_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
dut_fcmp_32ns_32ns_1_1_U121(
    .din0(reg_174),
    .din1(ap_const_lv32_0),
    .opcode(ap_const_lv5_2),
    .dout(tmp_14_fu_169_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(1'b0 == exitcond_fu_202_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b0 == exitcond_reg_333) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_7))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b1;
        end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) | ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_7) & ~(1'b0 == exitcond_reg_333)))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_7)) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_7)) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_7)) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_7)) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_7)) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            ap_reg_ppiten_pp0_it6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (1'b0 == exitcond_reg_333))) begin
        m_reg_143 <= m_3_reg_337;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        m_reg_143 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st37_fsm_8)) begin
        n_reg_119 <= n_1_reg_308;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        n_reg_119 <= ap_const_lv9_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == ap_reg_ppstg_exitcond_reg_333_pp0_iter2) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_6))) begin
        one_out_reg_131 <= one_out_1_reg_371;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        one_out_reg_131 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3)) begin
        ap_reg_ppstg_exitcond_reg_333_pp0_iter1 <= exitcond_reg_333;
        ap_reg_ppstg_exitcond_reg_333_pp0_iter2 <= ap_reg_ppstg_exitcond_reg_333_pp0_iter1;
        ap_reg_ppstg_ifzero_reg_352_pp0_iter1 <= ifzero_reg_352;
        ap_reg_ppstg_ifzero_reg_352_pp0_iter2 <= ap_reg_ppstg_ifzero_reg_352_pp0_iter1;
        ap_reg_ppstg_ifzero_reg_352_pp0_iter3 <= ap_reg_ppstg_ifzero_reg_352_pp0_iter2;
        ap_reg_ppstg_ifzero_reg_352_pp0_iter4 <= ap_reg_ppstg_ifzero_reg_352_pp0_iter3;
        ap_reg_ppstg_ifzero_reg_352_pp0_iter5 <= ap_reg_ppstg_ifzero_reg_352_pp0_iter4;
        ap_reg_ppstg_ifzero_reg_352_pp0_iter6 <= ap_reg_ppstg_ifzero_reg_352_pp0_iter5;
        exitcond_reg_333 <= exitcond_fu_202_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        b_fc1_load_reg_328 <= b_fc1_q0;
        n_cast4_reg_323[8 : 0] <= n_cast4_fu_198_p1[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (1'b0 == exitcond_fu_202_p2))) begin
        ifzero_reg_352 <= ifzero_fu_241_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3))) begin
        m_3_reg_337 <= m_3_fu_208_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        n_1_reg_308 <= n_1_fu_186_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_5) & (1'b0 == ap_reg_ppstg_exitcond_reg_333_pp0_iter2))) begin
        one_out_1_reg_371 <= grp_fu_154_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it5) & ~(ap_reg_ppstg_ifzero_reg_352_pp0_iter4 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3))) begin
        one_out_2_reg_382 <= grp_fu_160_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_180_p2))) begin
        output_addr_reg_318[8 : 0] <= tmp_4_fu_192_p1[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it4) & ~(ap_reg_ppstg_ifzero_reg_352_pp0_iter4 == 1'b0)) | ((1'b1 == ap_reg_ppiten_pp0_it6) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(1'b0 == ap_reg_ppstg_ifzero_reg_352_pp0_iter5)))) begin
        reg_174 <= grp_fu_154_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_5) & (1'b0 == ap_reg_ppstg_exitcond_reg_333_pp0_iter1))) begin
        tmp_11_reg_366 <= grp_fu_166_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_4) & ~(1'b0 == ap_reg_ppstg_ifzero_reg_352_pp0_iter6))) begin
        tmp_15_reg_387 <= tmp_15_fu_299_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_4) & (1'b0 == exitcond_reg_333))) begin
        tmp_7_reg_356 <= tmp_7_fu_253_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it3) & ~(1'b0 == ap_reg_ppstg_ifzero_reg_352_pp0_iter3))) begin
        tmp_8_reg_377 <= grp_fu_160_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | ((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_180_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_180_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_97) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_69) begin
        ap_sig_cseq_ST_pp0_stg1_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg1_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_166) begin
        ap_sig_cseq_ST_pp0_stg2_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg2_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_223) begin
        ap_sig_cseq_ST_pp0_stg3_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg3_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_198) begin
        ap_sig_cseq_ST_pp0_stg4_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg4_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_26) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_112) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_215) begin
        ap_sig_cseq_ST_st37_fsm_8 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st37_fsm_8 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_128) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        b_fc1_ce0 = 1'b1;
    end else begin
        b_fc1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it5))) begin
        grp_fu_154_p0 = one_out_2_reg_382;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it3) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_5))) begin
        grp_fu_154_p0 = tmp_8_reg_377;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_6))) begin
        grp_fu_154_p0 = one_out_phi_fu_135_p4;
    end else begin
        grp_fu_154_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it5))) begin
        grp_fu_154_p1 = b_fc1_load_reg_328;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it3) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_5))) begin
        grp_fu_154_p1 = ap_const_lv32_C4000000;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_6))) begin
        grp_fu_154_p1 = tmp_11_reg_366;
    end else begin
        grp_fu_154_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it4) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_5))) begin
        grp_fu_160_p0 = reg_174;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_6))) begin
        grp_fu_160_p0 = one_out_1_reg_371;
    end else begin
        grp_fu_160_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it4) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_5))) begin
        grp_fu_160_p1 = ap_const_lv32_3D800000;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_6))) begin
        grp_fu_160_p1 = ap_const_lv32_40000000;
    end else begin
        grp_fu_160_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3))) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (1'b0 == exitcond_reg_333))) begin
        m_phi_fu_147_p4 = m_3_reg_337;
    end else begin
        m_phi_fu_147_p4 = m_reg_143;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == ap_reg_ppstg_exitcond_reg_333_pp0_iter2) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_6))) begin
        one_out_phi_fu_135_p4 = one_out_1_reg_371;
    end else begin
        one_out_phi_fu_135_p4 = one_out_reg_131;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it6) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_5))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it6) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_5) & ~(1'b0 == ap_reg_ppstg_ifzero_reg_352_pp0_iter6))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3))) begin
        w_fc1_ce0 = 1'b1;
    end else begin
        w_fc1_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if (~(1'b0 == exitcond1_fu_180_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st3_fsm_2 : begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
        end
        ap_ST_pp0_stg0_fsm_3 : begin
            if (~((1'b1 == ap_reg_ppiten_pp0_it0) & ~(1'b0 == exitcond_fu_202_p2) & ~(1'b1 == ap_reg_ppiten_pp0_it1))) begin
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st37_fsm_8;
            end
        end
        ap_ST_pp0_stg1_fsm_4 : begin
            ap_NS_fsm = ap_ST_pp0_stg2_fsm_5;
        end
        ap_ST_pp0_stg2_fsm_5 : begin
            if (~((1'b1 == ap_reg_ppiten_pp0_it6) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_5) & ~(1'b1 == ap_reg_ppiten_pp0_it5))) begin
                ap_NS_fsm = ap_ST_pp0_stg3_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st37_fsm_8;
            end
        end
        ap_ST_pp0_stg3_fsm_6 : begin
            ap_NS_fsm = ap_ST_pp0_stg4_fsm_7;
        end
        ap_ST_pp0_stg4_fsm_7 : begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
        end
        ap_ST_st37_fsm_8 : begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_sig_112 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_128 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_166 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_198 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_215 = (1'b1 == ap_CS_fsm[ap_const_lv32_8]);
end

always @ (*) begin
    ap_sig_223 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_26 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_69 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_97 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

assign b_fc1_address0 = tmp_4_fu_192_p1;

assign biased_to_int_fu_263_p1 = reg_174;

assign exitcond1_fu_180_p2 = ((n_reg_119 == ap_const_lv9_100) ? 1'b1 : 1'b0);

assign exitcond_fu_202_p2 = ((m_phi_fu_147_p4 == ap_const_lv10_200) ? 1'b1 : 1'b0);

assign grp_fu_166_p0 = tmp_7_reg_356;

assign ifzero_fu_241_p2 = ((m_3_fu_208_p2 == ap_const_lv10_200) ? 1'b1 : 1'b0);

assign input_r_address0 = newIndex8_fu_231_p1;

assign m_3_fu_208_p2 = (m_phi_fu_147_p4 + ap_const_lv10_1);

assign n_1_fu_186_p2 = (n_reg_119 + ap_const_lv9_1);

assign n_cast4_fu_198_p1 = n_reg_119;

assign newIndex8_fu_231_p1 = m_phi_fu_147_p4;

assign notlhs_fu_281_p2 = ((tmp_fu_267_p4 != ap_const_lv8_FF) ? 1'b1 : 1'b0);

assign notrhs_fu_287_p2 = ((tmp_22_fu_277_p1 == ap_const_lv23_0) ? 1'b1 : 1'b0);

assign output_r_address0 = output_addr_reg_318;

assign output_r_d0 = tmp_15_reg_387;

assign tmp1_fu_247_p2 = (input_r_q0 ^ 1'b1);

assign tmp_13_fu_293_p2 = (notrhs_fu_287_p2 | notlhs_fu_281_p2);

assign tmp_15_fu_299_p2 = (tmp_13_fu_293_p2 & tmp_14_fu_169_p2);

assign tmp_21_fu_214_p1 = m_phi_fu_147_p4[8:0];

assign tmp_22_fu_277_p1 = biased_to_int_fu_263_p1[22:0];

assign tmp_4_fu_192_p1 = n_reg_119;

assign tmp_6_fu_236_p1 = w_index_fu_226_p2;

assign tmp_7_fu_253_p2 = (w_fc1_q0 ^ tmp1_fu_247_p2);

assign tmp_9_fu_218_p3 = {{tmp_21_fu_214_p1}, {ap_const_lv8_0}};

assign tmp_fu_267_p4 = {{biased_to_int_fu_263_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign w_fc1_address0 = tmp_6_fu_236_p1;

assign w_index_fu_226_p2 = (n_cast4_reg_323 + tmp_9_fu_218_p3);

always @ (posedge ap_clk) begin
    output_addr_reg_318[9] <= 1'b0;
    n_cast4_reg_323[16:9] <= 8'b00000000;
end

endmodule //dut_dense_1
