lappend pragmaStatus0 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "max_pool" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "input"}
lappend pragmaStatus1 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "max_pool" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "output"}
lappend pragmaStatus2 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'conv' does not exist in any synthesis source file." variable "input"}
lappend pragmaStatus3 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'conv' does not exist in any synthesis source file." variable "output"}
lappend pragmaStatus4 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "reshape/LOOP_RESHAPE_1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "reshape/LOOP_RESHAPE_2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv/LOOP_N" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus7 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv/LOOP_X" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus8 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv/LOOP_Y" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus9 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv/LOOP_M" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus10 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv/LOOP_C" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus11 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv/LOOP_R" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus12 {pragma "PIPELINE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv/LOOP_N" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus13 {pragma "ARRAY_RESHAPE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "input"}
lappend pragmaStatus14 {pragma "ARRAY_RESHAPE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "output"}
lappend pragmaStatus15 {pragma "ARRAY_RESHAPE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "dense_mlp" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "input"}
lappend pragmaStatus16 {pragma "ARRAY_RESHAPE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "dense_mlp" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "output"}
lappend pragmaStatus17 {pragma "ARRAY_RESHAPE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "max_pool" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "input"}
lappend pragmaStatus18 {pragma "ARRAY_RESHAPE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "max_pool" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "output"}
lappend pragmaStatus19 {pragma "LOOP_MERGE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_MERGE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus20 {pragma "LOOP_MERGE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "dense_mlp" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus21 {pragma "EXPRESSION_BALANCE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'EXPRESSION_BALANCE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus22 {pragma "EXPRESSION_BALANCE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "dense_mlp" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus23 {pragma "EXPRESSION_BALANCE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "max_pool" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus24 {pragma "LATENCY" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv/LOOP_N" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LATENCY' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus25 {pragma "LATENCY" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv/LOOP_X" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LATENCY' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus26 {pragma "LATENCY" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv/LOOP_Y" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LATENCY' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus27 {pragma "LATENCY" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv/LOOP_M" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LATENCY' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus28 {pragma "LATENCY" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv/LOOP_C" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LATENCY' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus29 {pragma "LATENCY" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv/LOOP_R" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LATENCY' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus30 {pragma "INLINE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus31 {pragma "INLINE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "dense_mlp" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus32 {pragma "INLINE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/layer.cpp" location "max_pool" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus0 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "max_pool" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'max_pool' does not exist in any synthesis source file." variable "input"}
lappend pragmaStatus1 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "max_pool" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'max_pool' does not exist in any synthesis source file." variable "output"}
lappend pragmaStatus2 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'conv' does not exist in any synthesis source file." variable "input"}
lappend pragmaStatus3 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'conv' does not exist in any synthesis source file." variable "output"}
lappend pragmaStatus4 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "reshape/LOOP_RESHAPE_1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'reshape' does not exist in any synthesis source file."}
lappend pragmaStatus5 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "reshape/LOOP_RESHAPE_2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'reshape' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv/LOOP_N" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus7 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv/LOOP_X" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus8 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv/LOOP_Y" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus9 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv/LOOP_M" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus10 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv/LOOP_C" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus11 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv/LOOP_R" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus12 {pragma "PIPELINE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv/LOOP_N" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus13 {pragma "ARRAY_RESHAPE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_RESHAPE' cannot be applied: Function 'conv1' does not exist in any synthesis source file." variable "input"}
lappend pragmaStatus14 {pragma "ARRAY_RESHAPE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_RESHAPE' cannot be applied: Function 'conv1' does not exist in any synthesis source file." variable "output"}
lappend pragmaStatus15 {pragma "ARRAY_RESHAPE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "dense_mlp" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_RESHAPE' cannot be applied: Function 'dense_mlp' does not exist in any synthesis source file." variable "input"}
lappend pragmaStatus16 {pragma "ARRAY_RESHAPE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "dense_mlp" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_RESHAPE' cannot be applied: Function 'dense_mlp' does not exist in any synthesis source file." variable "output"}
lappend pragmaStatus17 {pragma "ARRAY_RESHAPE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "max_pool" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_RESHAPE' cannot be applied: Function 'max_pool' does not exist in any synthesis source file." variable "input"}
lappend pragmaStatus18 {pragma "ARRAY_RESHAPE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "max_pool" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_RESHAPE' cannot be applied: Function 'max_pool' does not exist in any synthesis source file." variable "output"}
lappend pragmaStatus19 {pragma "LOOP_MERGE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_MERGE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus20 {pragma "LOOP_MERGE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "dense_mlp" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_MERGE' cannot be applied: Function 'dense_mlp' does not exist in any synthesis source file."}
lappend pragmaStatus21 {pragma "EXPRESSION_BALANCE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'EXPRESSION_BALANCE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus22 {pragma "EXPRESSION_BALANCE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "dense_mlp" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'EXPRESSION_BALANCE' cannot be applied: Function 'dense_mlp' does not exist in any synthesis source file."}
lappend pragmaStatus23 {pragma "EXPRESSION_BALANCE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "max_pool" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'EXPRESSION_BALANCE' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
lappend pragmaStatus24 {pragma "LATENCY" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv/LOOP_N" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LATENCY' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus25 {pragma "LATENCY" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv/LOOP_X" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LATENCY' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus26 {pragma "LATENCY" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv/LOOP_Y" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LATENCY' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus27 {pragma "LATENCY" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv/LOOP_M" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LATENCY' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus28 {pragma "LATENCY" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv/LOOP_C" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LATENCY' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus29 {pragma "LATENCY" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv/LOOP_R" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LATENCY' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus30 {pragma "INLINE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus31 {pragma "INLINE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "dense_mlp" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'dense_mlp' does not exist in any synthesis source file."}
lappend pragmaStatus32 {pragma "INLINE" source "/home/nrb74/ece5775/ECE5775_Final_Proj/lab4_modified/ecelinux/mlp.cpp" location "max_pool" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
