lappend pragmaStatus0 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv/LOOP_N" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv/LOOP_X" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv/LOOP_Y" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv/LOOP_M" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv/LOOP_C" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv/LOOP_R" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool/LOOP_MAX_POOL_0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool/LOOP_MAX_POOL_1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool/LOOP_MAX_POOL_2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool/LOOP_MAX_POOL_3" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool/LOOP_MAX_POOL_4" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus11 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool/LOOP_MAX_POOL_5" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus12 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "reshape/LOOP_RESHAPE_0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus13 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "reshape/LOOP_RESHAPE_1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus14 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "dense/LOOP_DENSE_0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus15 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "dense/LOOP_DENSE_1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus16 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "pad" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "input"}
lappend pragmaStatus17 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "pad" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "output"}
lappend pragmaStatus18 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "input"}
lappend pragmaStatus19 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "output"}
lappend pragmaStatus20 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "input"}
lappend pragmaStatus21 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "output"}
lappend pragmaStatus22 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "threshold"}
lappend pragmaStatus23 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv/LOOP_N" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus24 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv/LOOP_X" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus25 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv/LOOP_Y" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus26 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv/LOOP_M" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus27 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv/LOOP_C" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus28 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "conv/LOOP_R" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus29 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool/LOOP_MAX_POOL_0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus30 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool/LOOP_MAX_POOL_1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus31 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool/LOOP_MAX_POOL_2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus32 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool/LOOP_MAX_POOL_3" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus33 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool/LOOP_MAX_POOL_4" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus34 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "max_pool/LOOP_MAX_POOL_5" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus35 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "reshape/LOOP_RESHAPE_0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus36 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "reshape/LOOP_RESHAPE_1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus37 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "reshape/LOOP_RESHAPE_2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus38 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "dense/LOOP_DENSE_0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus39 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/layer.cpp" location "dense/LOOP_DENSE_1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus0 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv/LOOP_N" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv/LOOP_X" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv/LOOP_Y" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv/LOOP_M" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv/LOOP_C" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus5 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv/LOOP_R" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool/LOOP_MAX_POOL_0" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
lappend pragmaStatus7 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool/LOOP_MAX_POOL_1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
lappend pragmaStatus8 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool/LOOP_MAX_POOL_2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
lappend pragmaStatus9 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool/LOOP_MAX_POOL_3" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
lappend pragmaStatus10 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool/LOOP_MAX_POOL_4" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
lappend pragmaStatus11 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool/LOOP_MAX_POOL_5" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
lappend pragmaStatus12 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "reshape/LOOP_RESHAPE_0" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'reshape' does not exist in any synthesis source file."}
lappend pragmaStatus13 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "reshape/LOOP_RESHAPE_1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'reshape' does not exist in any synthesis source file."}
lappend pragmaStatus14 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "dense/LOOP_DENSE_0" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'dense' does not exist in any synthesis source file."}
lappend pragmaStatus15 {pragma "PIPELINE" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "dense/LOOP_DENSE_1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'dense' does not exist in any synthesis source file."}
lappend pragmaStatus16 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "pad" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'pad' does not exist in any synthesis source file." variable "input"}
lappend pragmaStatus17 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "pad" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'pad' does not exist in any synthesis source file." variable "output"}
lappend pragmaStatus18 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'max_pool' does not exist in any synthesis source file." variable "input"}
lappend pragmaStatus19 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'max_pool' does not exist in any synthesis source file." variable "output"}
lappend pragmaStatus20 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'conv' does not exist in any synthesis source file." variable "input"}
lappend pragmaStatus21 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'conv' does not exist in any synthesis source file." variable "output"}
lappend pragmaStatus22 {pragma "ARRAY_PARTITION" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'conv' does not exist in any synthesis source file." variable "threshold"}
lappend pragmaStatus23 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv/LOOP_N" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus24 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv/LOOP_X" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus25 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv/LOOP_Y" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus26 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv/LOOP_M" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus27 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv/LOOP_C" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus28 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "conv/LOOP_R" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'conv' does not exist in any synthesis source file."}
lappend pragmaStatus29 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool/LOOP_MAX_POOL_0" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
lappend pragmaStatus30 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool/LOOP_MAX_POOL_1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
lappend pragmaStatus31 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool/LOOP_MAX_POOL_2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
lappend pragmaStatus32 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool/LOOP_MAX_POOL_3" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
lappend pragmaStatus33 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool/LOOP_MAX_POOL_4" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
lappend pragmaStatus34 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "max_pool/LOOP_MAX_POOL_5" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'max_pool' does not exist in any synthesis source file."}
lappend pragmaStatus35 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "reshape/LOOP_RESHAPE_0" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'reshape' does not exist in any synthesis source file."}
lappend pragmaStatus36 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "reshape/LOOP_RESHAPE_1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'reshape' does not exist in any synthesis source file."}
lappend pragmaStatus37 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "reshape/LOOP_RESHAPE_2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'reshape' does not exist in any synthesis source file."}
lappend pragmaStatus38 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "dense/LOOP_DENSE_0" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'dense' does not exist in any synthesis source file."}
lappend pragmaStatus39 {pragma "LOOP_UNROLL" source "/home/nrb74/ece5775/lab4/ecelinux/bnn.cpp" location "dense/LOOP_DENSE_1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_UNROLL' cannot be applied: Function 'dense' does not exist in any synthesis source file."}
