// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _matmult_HH_
#define _matmult_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "matmult_fadd_32ns_32ns_32_5_full_dsp.h"
#include "matmult_fmul_32ns_32ns_32_4_max_dsp.h"

namespace ap_rtl {

struct matmult : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<14> > a_address0;
    sc_out< sc_logic > a_ce0;
    sc_in< sc_lv<32> > a_q0;
    sc_out< sc_lv<14> > b_address0;
    sc_out< sc_logic > b_ce0;
    sc_in< sc_lv<32> > b_q0;
    sc_out< sc_lv<14> > out_r_address0;
    sc_out< sc_logic > out_r_ce0;
    sc_out< sc_logic > out_r_we0;
    sc_out< sc_lv<32> > out_r_d0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    matmult(sc_module_name name);
    SC_HAS_PROCESS(matmult);

    ~matmult();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    matmult_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>* matmult_fadd_32ns_32ns_32_5_full_dsp_U1;
    matmult_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>* matmult_fmul_32ns_32ns_32_4_max_dsp_U2;
    sc_signal< sc_lv<13> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_28;
    sc_signal< sc_lv<14> > next_mul2_fu_157_p2;
    sc_signal< sc_lv<14> > next_mul2_reg_245;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_61;
    sc_signal< sc_lv<7> > i_1_fu_169_p2;
    sc_signal< sc_lv<7> > i_1_reg_253;
    sc_signal< sc_lv<7> > j_1_fu_181_p2;
    sc_signal< sc_lv<7> > j_1_reg_261;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_72;
    sc_signal< sc_lv<14> > tmp_2_cast_fu_187_p1;
    sc_signal< sc_lv<14> > tmp_2_cast_reg_266;
    sc_signal< sc_lv<1> > exitcond1_fu_175_p2;
    sc_signal< sc_lv<14> > out_addr_reg_271;
    sc_signal< sc_lv<7> > k_1_fu_208_p2;
    sc_signal< sc_lv<7> > k_1_reg_279;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_89;
    sc_signal< sc_lv<1> > exitcond_fu_202_p2;
    sc_signal< sc_lv<14> > next_mul_fu_229_p2;
    sc_signal< sc_lv<14> > next_mul_reg_289;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_106;
    sc_signal< sc_lv<32> > grp_fu_151_p2;
    sc_signal< sc_lv<32> > tmp_6_reg_309;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_116;
    sc_signal< sc_lv<32> > grp_fu_146_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st13_fsm_12;
    sc_signal< bool > ap_sig_125;
    sc_signal< sc_lv<7> > i_reg_77;
    sc_signal< sc_lv<14> > phi_mul1_reg_88;
    sc_signal< sc_lv<7> > j_reg_100;
    sc_signal< sc_lv<1> > exitcond2_fu_163_p2;
    sc_signal< sc_lv<32> > storemerge_reg_111;
    sc_signal< sc_lv<7> > k_reg_124;
    sc_signal< sc_lv<14> > phi_mul_reg_135;
    sc_signal< sc_lv<64> > tmp_9_cast_fu_197_p1;
    sc_signal< sc_lv<64> > tmp_10_cast_fu_224_p1;
    sc_signal< sc_lv<64> > tmp_12_cast_fu_240_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_162;
    sc_signal< sc_lv<14> > tmp_9_fu_191_p2;
    sc_signal< sc_lv<14> > tmp_5_cast_fu_214_p1;
    sc_signal< sc_lv<14> > tmp_s_fu_218_p2;
    sc_signal< sc_lv<14> > tmp_2_fu_235_p2;
    sc_signal< sc_lv<13> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<13> ap_ST_st1_fsm_0;
    static const sc_lv<13> ap_ST_st2_fsm_1;
    static const sc_lv<13> ap_ST_st3_fsm_2;
    static const sc_lv<13> ap_ST_st4_fsm_3;
    static const sc_lv<13> ap_ST_st5_fsm_4;
    static const sc_lv<13> ap_ST_st6_fsm_5;
    static const sc_lv<13> ap_ST_st7_fsm_6;
    static const sc_lv<13> ap_ST_st8_fsm_7;
    static const sc_lv<13> ap_ST_st9_fsm_8;
    static const sc_lv<13> ap_ST_st10_fsm_9;
    static const sc_lv<13> ap_ST_st11_fsm_10;
    static const sc_lv<13> ap_ST_st12_fsm_11;
    static const sc_lv<13> ap_ST_st13_fsm_12;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<14> ap_const_lv14_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<14> ap_const_lv14_64;
    static const sc_lv<7> ap_const_lv7_64;
    static const sc_lv<7> ap_const_lv7_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_a_address0();
    void thread_a_ce0();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_106();
    void thread_ap_sig_116();
    void thread_ap_sig_125();
    void thread_ap_sig_162();
    void thread_ap_sig_28();
    void thread_ap_sig_61();
    void thread_ap_sig_72();
    void thread_ap_sig_89();
    void thread_ap_sig_cseq_ST_st13_fsm_12();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_b_address0();
    void thread_b_ce0();
    void thread_exitcond1_fu_175_p2();
    void thread_exitcond2_fu_163_p2();
    void thread_exitcond_fu_202_p2();
    void thread_i_1_fu_169_p2();
    void thread_j_1_fu_181_p2();
    void thread_k_1_fu_208_p2();
    void thread_next_mul2_fu_157_p2();
    void thread_next_mul_fu_229_p2();
    void thread_out_r_address0();
    void thread_out_r_ce0();
    void thread_out_r_d0();
    void thread_out_r_we0();
    void thread_tmp_10_cast_fu_224_p1();
    void thread_tmp_12_cast_fu_240_p1();
    void thread_tmp_2_cast_fu_187_p1();
    void thread_tmp_2_fu_235_p2();
    void thread_tmp_5_cast_fu_214_p1();
    void thread_tmp_9_cast_fu_197_p1();
    void thread_tmp_9_fu_191_p2();
    void thread_tmp_s_fu_218_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
